version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    

    ports:
      # HTTP
      - 9191:9191

    environment:
      NIFI_WEB_HTTP_PORT: 9191
    
    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
